### ISSUE TITLE
Is it possible to run nuxtClientInit before components?

### ISSUE THREAD

**Issue by awronski** [potato4d/nuxt-client-init-module#5]
Hi!

I need to set store state on the client side but before components mounted.
Now the `nuxtClientInit` fires after the components, so the components don't see the state.

Thanks!

**Comment by smyth64** [comment]
Yeah this is really annoying. That's why I just use a plugin instead of this module. What's the purpose of a nuxtClientInit when it's not firing before the components??

**Comment by potato4d** [comment]
I am waiting for a Pull Request to improve it
