### ISSUE TITLE
[Suggestion] Multiple entry points for nuxtClientInit.

### ISSUE THREAD

**Issue by cdrandin** [potato4d/nuxt-client-init-module#6]
Similar to how nuxtServerInit can work from multiple namespaced scopes.

This is my naive approach to it.

```Javascript
export default(context) => {
  if (process.browser) {
    setTimeout(() => {
      context.store.dispatch('nuxtClientInit', context)

      const actions = Object.keys(context.store._actions).filter(k => k.includes('/nuxtClientInit'))
      actions.forEach(function(a) {
        context.store.dispatch(a, context)
      });
    }, 0)
  }
}
```

Couple things to note:
* It guarantees root nuxtClientInit runs first.
* Could be a problem if there are many nuxtClientInit and/or take long to process.

**Comment by potato4d** [comment]
This module is intended to complement the functionality missing from the Nuxt.js core.

Therefore, we respect core policy and do not implement this feature.

> If you are using the Modules mode of the Vuex store, only the primary module (in store / index.js) will receive this action.You'll need to chain your module actions from there.

https://nuxtjs.org/guide/vuex-store/#the-nuxtserverinit-action
