### ISSUE TITLE
Documentation request: a note on module order importance

### ISSUE THREAD

**Issue by gbezyuk** [potato4d/nuxt-client-init-module#62]
Hi there. There is an important thing I'd like to be underscored in the readme. When using `nuxt-client-init-module` together with `@nuxtjs/axios`, it's important to use this order of modules:
```js
{
//...
modules: [
    'nuxt-client-init-module', // should come first
    '@nuxtjs/axios',
  ],
}
```
and not this one:
```js
{
//...
modules: [
    '@nuxtjs/axios', // DON'T DO IT! if axios comes first, clientInit won't see it
    'nuxt-client-init-module',
  ],
}
```

Otherwise, this code:

```js
actions = {
  nuxtServerInit ( {
    console.log('server init: AXIOS is available', !!this.$axios) // TRUE, as it should be
  },

  nuxtClientInit ({ state, dispatch }) {
    console.log('client init: AXIOS is available', !!this.$axios) // FALSE if the order is wrong
  }
}
```

will return `true` on server, but `false` on the client, thus causing obvious troubles.

**Comment by kamikazechaser** [comment]
This is such an important caveat and still remains undocumented, @potato4d should I send in a PR for README.md ?

**Comment by potato4d** [comment]
@kamikazechaser :heart:
