### ISSUE TITLE
How to run nuxtClientInit after plugins initialized ?

### ISSUE THREAD

**Issue by cyberz** [potato4d/nuxt-client-init-module#65]
My client intialization code use plugins, and  I got errors like this

`TypeError: this.$myPlugin is not a function`

It is possible to run nuxtClientInit after plugins initialized ?

**Comment by therealwolf42** [comment]
I had a similar issue. Nuxt is supposed to load the modules in the order based on the nuxt.config file. However, in my case, the order was completely different. If you really need to wait for the initialization, the quickest way to achieve this, is to call emulate `nuxtClientInit` yourself.

For example: 

https://github.com/therealwolf42/nuxt-socket.io-module/blob/master/lib/plugin.js#L20

```
plugin.js
export default async (context) => {
  if(process.browser) {
    // ... your code

    await context.store.dispatch('readySteadyGo', context)
  }
}
```

**Comment by MrJmpl3** [comment]
I have this problem too. @potato4d, Please try to fix, or add a warning about this issue 😁

**Comment by hatta-pivot** [comment]
@potato4d 
自分の場合はiOSのsafariでだけ、この現象が発生しました。
クライアントサイドでmoduleの初期化がpluginの初期化後に実施されるというのはNuxtの仕様で決まっているのでしょうか。
こちらはいったんonNuxtReadyに切り替えました。

**Comment by sergiocastrovale** [comment]
Also need this. I feel like this is a very common usage pattern, there are lots of (global) plugins that the project needs beforehand and without that the functionality of this package - which is a great idea - becomes useless.

**Comment by timothymarois** [comment]
I'd also like to say I just saw the same issue, as I see these globally injected variables from plugins, they are there in context output, but I am unable to access them. To me it kind of defeats the purpose of using this module.

**Comment by timothymarois** [comment]
The solution by @therealwolf42  successfully works in my case. Loaded it as a plugin and gives access to all the needed plugin variables in a custom init method.
